### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [daangijzen/graduation#1]
Hello, <br/> <br/>I'm the creator of the Feel, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by daangijzen** [comment]
Oh! Sorry! This was not my intention!

Will making the repository private be enough?

Cause I’m a noob with git 😅

**Comment by daangijzen** [comment]
@reunono I'll also try and delete all the associated files in te meantime. 

Sorry for this dumb mistake!

**Comment by reunono** [comment]
Yes, as explained in my message above, making the repo private will be enough.

**Comment by daangijzen** [comment]
@reunono I think I deleted it from my git.

Again, my apologies!
